### ISSUE TITLE
Reviewer groups drop down only shows up in Edit mode on Atlassian Stash v3.1.0

### ISSUE THREAD

**Issue by millent** [dragouf/Stash-Reviewers-Chrome-Extension#1]
Hi 

Great plugin! Just wanted to report an issue that I had when I tried to use the plugin - the drop down does not show up in the Create Pull request page with Atlassian Stash v3.1.0. Perhaps the control id-s have changed ... It does work in Edit Pull request. 

Best regards

Millen

**Comment by dragouf** [comment]
I made lots of changes since last commit here. I will publish the updated code soon here. Current code I use works with 3.1.0.

**Comment by dragouf** [comment]
Ok I just committed last source code. 
Note that it will also add many other features (which you can disable easily in source code). And you will also need to edit all the &lt;your_stash_domain_here&gt; occurrence in code to enable all features.
In chrome plugin it's in manifest.json and in firefox plugin edit xpi with zip editor and edit main.js

Please give me feedback to tell me if it works since I don't have time to test.

**Comment by millent** [comment]
Hey dragouf

just tried it out. Replaced stash domain in 2 occurences in manifest.json
but it didn't work at all.

**Comment by dragouf** [comment]
What you mean by nothing is working ? Note that you also must define reviewers groups by clicking on extension icon on the right of the url bar or the extension won't be executed.

Without more information I can't guess what it is. Please open chrome console of stash website and also the one for background.js which you can open from chrome extension page and report me any error it display here.

**Comment by millent** [comment]
I am getting the below error in the stash page console. Nothing in
background page

batch.js?locale=en-US:1786 Uncaught Error: No stash/api/util/state


   1. A@batch.js?locale=en-US:1786require@batch.js?locale=en-US:1788(anonymous
      function)@stash_page_injector.js:1452(anonymous function)@
      stash_page_injector.js:1526

**Comment by dragouf** [comment]
ok, another question, on which page do you get this error ? All stash pages or a specific one ?

**Comment by millent** [comment]
seems to happen on all page e.g. branches, source, commits ... the error
ocurrs when the page loads for the first time (full load). Also only
happens when the extesion is enabled.

**Comment by dragouf** [comment]
can you execute this command in the chrome console and tell me if it load a library ? 

WRM.require("wr!" + 'com.atlassian.stash.stash-web-api:state')

If it works I can commit a fix quickly.

**Comment by millent** [comment]
looks like it does
-------------------------------------------
WRM.require("wr!" + 'com.atlassian.stash.stash-web-api:state')
Object {}always: ()done: ()fail: ()pipe: ()progress: ()promise: (a)state:
()then: ()__proto__: Object

**Comment by dragouf** [comment]
not sure, it should display a message like: resources downloaded. Here the output you copy is just the promise object. Anyway, I made a commit, can you try it to see if it fix the problem ?

**Comment by millent** [comment]
no time today ... tomorrow can check it

**Comment by david-resnick** [comment]
@dragouf I've tested the latest code in my environment and everything I've seen works great. 

Awesome plugin!

**Comment by dragouf** [comment]
Thanks for your feedback @david-resnick. If you implement any new functionality don't hesitate to send pull request.
