### ISSUE TITLE
Chrome Browser Crashing when Plugin Enabled

### ISSUE THREAD

**Issue by etzlers** [dragouf/Stash-Reviewers-Chrome-Extension#18]
When I have the plugin enabled for Chrome the browser will regularly crash on me and I will have to re-open it and my tabs. Do you have any advice or ideas on how I can resolve this issue? When I disable the plugin the browser no longer crashes and seems to work fine. (I have other co-workers who have seen this same issue)

**Comment by dragouf** [comment]
Which version of the plugin are you using ?

It may because of the server poll to check for new notifications. 
Anyway it never happened to me and I use everyday this plugin.
Hard to guess without debug information. 

I will try to add new option to disable server poll as soon as I have time to see if it's related to that.

**Comment by etzlers** [comment]
I am using 2.2.7. I will disable desktop notifications to see if that changes anything?

**Comment by etzlers** [comment]
The browser crashed about an hour and a half after disabling the desktop notifications. Is there anything I could provide you that would help?

**Comment by dragouf** [comment]
Desktop notification doesn't disable background polling to check for new notification. 

I pushed a new version (2.2.8) to development branch. I added in this version a new button in options panel to disable background polling. Can you try to use this version and disable background polling in options and then tell me if it works ?

**Comment by etzlers** [comment]
Of course! I'll update now and let you know how it goes!

**Comment by etzlers** [comment]
Is this warning ok?

There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.

**Comment by dragouf** [comment]
Yes there is no problem with that. This key is used by Firefox webextensions but chrome don't reconized it. Anyway there is no impact, chrome just ignore it.

**Comment by etzlers** [comment]
Change appears to be working fine, haven't seen browser crashing issues since updating.
