### ISSUE TITLE
Build status not visible

### ISSUE THREAD

**Issue by benys** [dragouf/Stash-Reviewers-Chrome-Extension#21]
Hi,

I have configured teamcity to push build status. Normal stash view shows column with this status (green or red sticker).

**Comment by dragouf** [comment]
true, I will add this information.

**Comment by dragouf** [comment]
@benys it is now available on `development` branch. 
Can you try it and tell me if it works ?

**Comment by benys** [comment]
@dragouf it works partly - i found a small bug.
My stash/bitbacket has address https://XXX.XXX.XXX/stash/ not https://XXX.XXX.XXX/

So ajax:
`	
function getPRBuildStatus(commitList) {
			var commitIds = commitList.map(function(pr) { return pr.commit });
			return jQuery.ajax('/rest/build-status/latest/commits/stats', {
				method: 'POST',
				headers: {
`
not work because it create request to: https://XXX.XXX.XXX/rest/build-status/latest/commits/stats . It should create request to: https://XXX.XXX.XXX/stash/rest/build-status/latest/commits/stats

**Comment by dragouf** [comment]
Hi @benys,

I will add a parameter to set the correct bitbucket server base url. Sorry I had no time to work on it. I may have more time soon and close this ticket.

**Comment by benys** [comment]
Hi,

No problem, i use modified version by me :-)
