### ISSUE TITLE
Centralised reviewers list

### ISSUE THREAD

**Issue by dhilipb** [dragouf/Stash-Reviewers-Chrome-Extension#24]
Love the extension.

Our team keeps changing and we'd like to have a centralised location to store the stash reviewers. Would love this feature in this extension.

**Comment by dragouf** [comment]
Hi @dhilipb,

It's lots of work and I don't have time to implement this feature. 
However if you want to work on this feature and send a PR for that you are welcome.

**Comment by carera** [comment]
+1!

**Comment by ra100** [comment]
I think this can be closed :)
