### ISSUE TITLE
Can't install on firefox

### ISSUE THREAD

**Issue by sturose** [dragouf/Stash-Reviewers-Chrome-Extension#27]
Firefox will no longer allow unsigned extensions to be installed and https://addons.mozilla.org/en-US/firefox/addon/bitbucket-server-extension/ does not lead to a verified version to install.

**Comment by dragouf** [comment]
yes I know, it ever pass the validation because of jquery library I use for option panel and I finally gave up to pass it. As soon as I have time I will try to fix that.

**Comment by PavelVanecek** [comment]
@dragouf I would like to work on this. Is jQuery the only issue? If there are some more reviewer comments can you please share it?

**Comment by dragouf** [comment]
@PavelVanecek yes it was just about jquery if I remember well. I see your PR. Thanks! If you want you can also commit it on firefox store. I'm happy to know this project is usefull for people and to see that it still can be improve by developers.

**Comment by kengorab** [comment]
Was this ever published on the firefox addons store? Stash Extension is honestly one of the things keeping me from switching from Chrome to Firefox at this point. I didn't see anything when searching "Stash Extension"; is it maybe called something else?

**Comment by PavelVanecek** [comment]
@kengorab weird. I have published it in the Firefox addon store, but I can no longer access it. The URL is https://addons.mozilla.org/en-US/firefox/addon/bitbucket-server-reviewers/ but it shows 404. The addon even shows up in [search results](https://addons.mozilla.org/en-US/firefox/search/?q=bitbucket) but again the link leads nowhere. I'll try to fix it.

**Comment by PavelVanecek** [comment]
I found out there was a naming conflict, details in https://github.com/mozilla/addons-frontend/issues/4071 and https://github.com/mozilla/addons-server/issues/7132

I have republished the extension as https://addons.mozilla.org/en-US/firefox/addon/bitbucket-server/. I will update the README
