### ISSUE TITLE
Dropdown button doesn't appear

### ISSUE THREAD

**Issue by damianpi** [dragouf/Stash-Reviewers-Chrome-Extension#3]
Hello,
At first, I just want to say that this plugin is really great. However, I have one problem with it. Whereas I was able to install the plugin (both on Firefox and Chrome), there is no button on the pull request page. The tool appears in the browser, so I am able to define and save groups, but the button to choose the group on the reviewers (pull request) page does not.
I am using Stash v.4.2.0, which is actually Bitbucket now. Is there any chance this will work properly, or am I doing something wrong?

Regards,
Damian

**Comment by dragouf** [comment]
Hi Damian,

Yes it seems they renamed everything in bitbucket server. I will create a new branch for that soon.

**Comment by dragouf** [comment]
It's fixed. You can find the working version onto 'bitbucket-server-version' here: 

https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/tree/bitbucket-server-version

**Comment by damianpi** [comment]
Thank you for your help!
It works great on Chrome, but not on Firefox. There, the dropdown button (near the Reviewers field) does not appear at all.

**Comment by dragouf** [comment]
Ah yes I made a big mistake. I used chrome api in ff extension. It should work now.

Also make sure that `xpinstall.signatures.required` in `about:config` is set to false to allow unsigned extension to be executed.

Please tell me if it works!

**Comment by damianpi** [comment]
Everything works great now, thank you! 
If I could only suggest one more small thing - the distribution can be renamed from "stash-reviewers..." to "bitbucket-reviewers..."

**Comment by dragouf** [comment]
Yes it would be better for understanding. Thanks for your suggestion.
