### ISSUE TITLE
Extension doesn't work V 2.2.10

### ISSUE THREAD

**Issue by guyisra** [dragouf/Stash-Reviewers-Chrome-Extension#31]
Starting on extension version 2.2.10 it no longer works in bitbucket 4.11.1

It worked fine on 2.2.8

**Comment by dragouf** [comment]
I merged a PR which made this error. I'll fix this soon.

**Comment by dragouf** [comment]
should be fixed with v2.2.11

**Comment by cjauvin** [comment]
Thank you, it works! :+1:
