### ISSUE TITLE
Update the extension on the Chrome store

### ISSUE THREAD

**Issue by dvoiss** [dragouf/Stash-Reviewers-Chrome-Extension#4]
The extension on the store was last updated on `October 28, 2015` which means it doesn't have the fix for the issue mentioned in [this ticket](https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/issues/1) and this [closed ticket](https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/issues/3).

That issue occurs for me when I use the plugin on the Chrome store but does not occur when I check out the repo and load the plugin.

**Comment by dragouf** [comment]
yes, the plugin on chrome store is still named stash and is still for stash. I haven't published the bitbucket version. 
For the moment new features need manual change to the manifest.json file to works, that's why I can't update the chrome store version.

**Comment by dragouf** [comment]
done!

there is now 2 versions on chrome webstore. 

for bitbucket server: https://chrome.google.com/webstore/detail/bitbucket-server-extensio/hlagecmhpppmpfdifmigdglnhcpnohib

and for stash server (v3) : https://chrome.google.com/webstore/detail/stash-reviewers/kpgdinlfgnkbfkmffilkgmeahphehegk

**Comment by david-resnick** [comment]
Is it now possible to use the extension without setting the stash domain in `manifest.json` and `main.js`?

**Comment by dragouf** [comment]
yes it is. Anyway the extension now check on every page if it's a stash/bitbucket page. To do that I did a small script to check global variable to avoid to inject the main script each time. 

But it was one of my concern. Do I have to ask the user to fill all there stash url or check by myself ?

But maybe some user will be annoyed to see this script inject on each page load and maybe I should write an input in extension options to allow user to specify there stash/bitbucket url. 

According to feedback I can change that later.^^

**Comment by david-resnick** [comment]
I work against exactly one Stash (soon to be Bitbucket) server and would rather configure the URL than have every page checked.

**Comment by dragouf** [comment]
Ok, I will try to allow user to specify there url when I have time.
