### ISSUE TITLE
Add reviewers button is missing

### ISSUE THREAD

**Issue by shark300** [dragouf/Stash-Reviewers-Chrome-Extension#49]
The add reviewers button is missing on Stash's create pull request page.

There is an error message on the console:
```
Uncaught TypeError: Cannot read property 'sendMessage' of undefined
    at stash_page.js:30
    at stash_page.js:2144
```

Browser version:
Google Chrome: 66.0.3359.139 (64 bit)

Plugin version:
Bitbucket Server Extension 2.2.12

**Comment by dragouf** [comment]
#50 merged and published to chrome store
