### ISSUE TITLE
Extension causes bitbucket inbox to be blank

### ISSUE THREAD

**Issue by MichaelTaylor3D** [dragouf/Stash-Reviewers-Chrome-Extension#52]
See image, after installing the extension the bitbucket inbox goes blank

![image](https://user-images.githubusercontent.com/5665004/40509929-09779dac-5f69-11e8-97eb-de6336f0905d.png)

**Comment by ra100** [comment]
I think it's the same issue as this PR fixes https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/pull/46

**Comment by dragouf** [comment]
merged and published.
