### ISSUE TITLE
Pull Requests list is empty (not "My Pull Requests")

### ISSUE THREAD

**Issue by mrvincenzo** [dragouf/Stash-Reviewers-Chrome-Extension#53]
Pull Request list is empty after the last upgrade to our BitBucket Server.

<img width="1626" alt="screen shot 2018-07-03 at 15 38 35" src="https://user-images.githubusercontent.com/5012608/42220755-9b23a050-7ed8-11e8-96ae-3d39f72bbba2.png">
<img width="1629" alt="screen shot 2018-07-03 at 15 39 12" src="https://user-images.githubusercontent.com/5012608/42220493-c877bb8c-7ed7-11e8-90d8-5e186b466c53.png">

**Comment by ra100** [comment]
Can you try if it's happening when you load extension from local folder, from this repo and branch?
`https://github.com/ra100/Stash-Reviewers-Chrome-Extension.git`
`45-empty-pullrequests-dropdow`

**Comment by mrvincenzo** [comment]
@ra100 Actually, the error occurs with your PR #46. I thought that issue #45 is the issue I described here and it was fixed, so I  pulled the PR and checked (loaded it to Chrome). Unfortunately, the issue does reproduce.

**Comment by ra100** [comment]
so good thing is, that fix for #45 didn't introduce this bug, now "just" to find out how to fix this

**Comment by dragouf** [comment]
Ok PR has been merged and code publish to chrome store.

**Comment by mrvincenzo** [comment]
@dragouf PR #46 didn't fix that. It fixed #45 but not this issue. This issue still reproduces.

**Comment by hagnat** [comment]
error reproduced and found on
Bitbucket v5.16.0
Bitbucket Server Extension 2.2.15
