### ISSUE TITLE
PR table isn't formatting properly

### ISSUE THREAD

**Issue by cnnranderson** [dragouf/Stash-Reviewers-Chrome-Extension#55]
When loading the Pull Requests page (where it lists out all the PRs that are open), it no longer succeeds at styling the table.

I receive the following error in the console:
`not able to load plugin PR filter table Error: No bitbucket/internal/feature/pull-request/table/pull-request-table`

This error is produced from a try/catch found on line 2117 in the `stash_page.js`.

Not really sure what's missing, but I wonder if it's my BitBucket enterprise version being either too up to date, or too old? Seems like a bitbucket source file it uses to parse out the table isn't available or being served by my BitBucket server anymore.

**Comment by ra100** [comment]
What's the version of your Bitbucket?

**Comment by cnnranderson** [comment]
v4.14.4

I think this version is actually kind of old, given it's an enterprise setup. Though, the plugin worked all up until about 2-3 weeks ago before the plugin version error issue came about (Issue #54)

**Comment by ra100** [comment]
That actually is very likely, that's the issue. As with latest update of extension, new bitbucket api is used (in PR list)

**Comment by cnnranderson** [comment]
Ah... yeah, I see it now in the latest [commits](https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/commit/8d05d812befd319b99dd2346ad46f48e494e9c4f).

Are there plans to keep the back support? I wonder if it's broken simply because `/table` was added in the `require()` call?

**Comment by ra100** [comment]
That might be it can you try to checkout repo, remove `table/` and load extension from folder? Then there could be try-catch block around that require, if it fails with "table" then try without

**Comment by cnnranderson** [comment]
Yep, that was going to be my first check. Turns out it fixes it!

I could try to make a PR in a bit with a conditional require check to see if one or the other loads?

**Comment by ra100** [comment]
I won't be able to check it sooner that in 12hrs. So if you create PR by then, I can check.

**Comment by cnnranderson** [comment]
#56 PR is up :) I'm a little weak with JS, but I can confirm this resolves the issue. It'd be nice if there's a way to check bitbucket version < 5.0 or something, but not immediately familiar with all the stuff going on in that script. Feel free to make any suggestions to improve the solution.
