### ISSUE TITLE
Dropdown is duplicated when you cancel a pull request and create a new one

### ISSUE THREAD

**Issue by incaronbus** [dragouf/Stash-Reviewers-Chrome-Extension#7]
I'm on Stash 3.7. Picture attached.

![screen shot 2016-04-06 at 6 02 40 pm](https://cloud.githubusercontent.com/assets/2607918/14337368/0fb09f4a-fc22-11e5-93a9-4b1a6ccddd91.png)

**Comment by dragouf** [comment]
Are you using the last version from this repository ? Or the one on chrome store ?
