### ISSUE TITLE
Clicking the extension icon no longer navigates to bitbucket

### ISSUE THREAD

**Issue by j0be** [dragouf/Stash-Reviewers-Chrome-Extension#71]
Prior to the latest release, clicking the icon would navigate to the bitbucket site you have locally. Mine is pointed to a internally hosted bitbucket server. 

Clicking the icon now shows this:

![Screen Shot 2020-10-29 at 15 37 01 ](https://user-images.githubusercontent.com/5649072/97623846-9e1bb100-19fc-11eb-8015-7bb090d3df2c.png)

Modifying this does nothing and will not save anything entered.

**Comment by Zykalus** [comment]
Same issue here. My hosted bitbucket server does not match the pattern given.

**Comment by premont** [comment]
same issue here
reinstalling did not change anything
type the a pattern that should work 
*://bitbucket:7990/*
and pressing save just brings back the same original pattern displayed

**Comment by ra100** [comment]
So it seems, that value is stored, but is not loaded/prefilled in the field.

**Comment by j0be** [comment]
I found why it's no longer launching. 

Here is the original code to handle the icon click:
![Screen Shot 2020-11-02 at 15 23 06 ](https://user-images.githubusercontent.com/5649072/97915458-835c7b80-1d1f-11eb-8293-15ff2e8df4a9.png)

Here is the documentation from Google regarding `chrome.browserAction.onClicked`:
![Screen Shot 2020-11-02 at 15 22 14 ](https://user-images.githubusercontent.com/5649072/97915523-9a02d280-1d1f-11eb-95a8-c90349676fef.png)

And here's the addition that caused it in `manifest.json`:
![Screen Shot 2020-11-02 at 15 23 19 ](https://user-images.githubusercontent.com/5649072/97915546-a4bd6780-1d1f-11eb-82d3-661940e5eeed.png)

https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/commit/17ec94edb8550742c77e052360f2820a02442aa8

**Comment by j0be** [comment]
I've created a pull request to fix this:
https://github.com/dragouf/Stash-Reviewers-Chrome-Extension/pull/72

**Comment by j0be** [comment]
@Zykalus. @premont, @BaconGirl, @jiemi

Feel free to update and test my fix to see if this fixes your issue. 

@ra100 / @premont, I'm pretty sure this issue can be closed as long as no one raises any concerns now the update is live

**Comment by guy-premont-cml** [comment]
Yes it works perfectly now. Thanks!

**Comment by BaconGirl** [comment]
Edit: I reinstalled the extension and I couldnt get it to work until I navigated to the dashboard url and then it started working by itself 😮

**Comment by j0be** [comment]
@BaconGirl, yeah. The extension stores a setting called `currentStashBaseUrl`, which is the last stash url you visited that matched your host filters. I'm not sure why that would get unset through normal activity. But on a new install, that wouldn't be set so it will need to have you browse to the stash url that matches your host filter before this fix works for it.
