### ISSUE TITLE
Extension doesn't work with Stash v2.12.2

### ISSUE THREAD

**Issue by willsheppard** [dragouf/Stash-Reviewers-Chrome-Extension#9]
First, I tried the extension from the Chrome store, it didn't work for our private instance of Stash.

Then I tried the developer version, I replaced <your_stash_domain_here> with the domain + port for our local Stash instance, e.g. `stash.example.com:8081`, this resulted in the following section of code in manifest.json:

      "matches": [
        "http://*/*/pull-requests?create*",
        "https://*/*/pull-requests?create*",

        "http://*/*/pull-requests/*/overview*",
        "https://*/*/pull-requests/*/overview*",

        "http://*/*/repos/*/browse*",
        "https://*/*/repos/*/browse*",

        "*://stash.example.com:8081/*"
      ]
    }
    ],
    "externally_connectable": {
  	"matches": ["*://stash.example.com:8081/*"]
    },

I then went to load the unpacked extension in Chrome, I pointed it to the `src` folder and got this error:

> Failed to load extension from: ~\AppData\CustomApps\Stash-Reviewers-Chrome-Extension\extension\chrome\src
> Invalid match pattern '*://stash.example.com:8081/*'
> 

And it listed the file starting with:
    {
    "manifest_version": 2,

**Comment by willsheppard** [comment]
Okay I've got past that error by changing this:

    "*://stash.example.com:8081/*"

to this:

    "https://stash.example.com:8081/*"

(i.e. adding "https" in place of the first asterisk).

Then I closed and re-opened Chrome, I defined the "groups" json with some groups and usernames again, and I reloaded the Stash page, and selected a branch. The title and description were automatically populated as usual, but no button appeared next to the Reviewers input field, nor did my user defined group appear when using autocomplete. What is supposed to happen exactly?

I even tried opening a new Chrome profile with all other extensions disabled, still nothing.

Atlassian Stash v2.12.2
Chrome 42.0.2311.152 (64-bit)

**Comment by willsheppard** [comment]
Our version of Stash isn't branded as BitBucket, could that mean it's an old, incompatible version?

If you give me a clue which parts of code I'd need to change for Stash v2.12.2, I could have a go at fixing it.

**Comment by dragouf** [comment]
Hi @willsheppard, 

There is a branch "stash-server-version" which is compatible with stash. 
But your version is very old. It was working with stash v3.10 and upper. but I can't tell if it works with v2.

If it doesn't work try to copy here what you get in chrome console. Maybe I can help with that.

**Comment by willsheppard** [comment]
I think this is what you're looking for - from the stash-server-version branch:

    batch.js:1696 Uncaught Error: No stash/api/util/state

I should mention our Stash instance is likely to be locked down pretty securely.

**Comment by dragouf** [comment]
@willsheppard, ah I see. 
So it use this stash javascript API: https://developer.atlassian.com/stash/docs/3.6.1/reference/javascript/state_.html 
but it seems there is no such api in stash 2.12.

According to this doc: https://developer.atlassian.com/stash/docs/3.6.1/reference/js-api.html

this api is available from v3.

So I think this extension can't be adapt to v2.

**Comment by willsheppard** [comment]
Ok fair enough
